USE DICTIONARY;
CREATE TABLE KEYWORDS(
	SQLKEY VARCHAR(20),
    PKEY INT
    );
CREATE TABLE KEYMAP(
	SYNON VARCHAR(20),
    FKEY INT 
    );
    
SELECT * FROM KEYWORDS;
SELECT * FROM KEYMAP;

SELECT RESULTANTTABLE.SQLKEY FROM (SELECT SQLKEY,SYNON FROM KEYWORDS 
NATURAL JOIN KEYMAP WHERE PKEY=FKEY) RESULTANTTABLE WHERE SYNON='RENEW';