-- ALTER
INSERT INTO KEYMAP VALUES('change', 6);
INSERT INTO KEYMAP VALUES('modify', 6);
INSERT INTO KEYMAP VALUES('adjust', 6);
INSERT INTO KEYMAP VALUES('transform', 6);
INSERT INTO KEYMAP VALUES('adapt', 6);
INSERT INTO KEYMAP VALUES('switch', 6);
INSERT INTO KEYMAP VALUES('vary', 6);
INSERT INTO KEYMAP VALUES('convert', 6);
INSERT INTO KEYMAP VALUES('update', 6);
INSERT INTO KEYMAP VALUES('revise', 6);
INSERT INTO KEYMAP VALUES('overhaul', 6);
INSERT INTO KEYMAP VALUES('shift', 6);

