-- DELETE
INSERT INTO KEYMAP VALUES('remove', 3);
INSERT INTO KEYMAP VALUES('erase', 3);
INSERT INTO KEYMAP VALUES('eliminate', 3);
INSERT INTO KEYMAP VALUES('get rid of', 3);
INSERT INTO KEYMAP VALUES('take away', 3);
INSERT INTO KEYMAP VALUES('clear', 3);
INSERT INTO KEYMAP VALUES('wipe of', 3);
INSERT INTO KEYMAP VALUES('expunge', 3);
INSERT INTO KEYMAP VALUES('discard', 3);
INSERT INTO KEYMAP VALUES('purify', 3);
INSERT INTO KEYMAP VALUES('cleanse', 3);
INSERT INTO KEYMAP VALUES('wash away', 3);