-- CREATE
INSERT INTO KEYMAP VALUES('make', 5);
INSERT INTO KEYMAP VALUES('build', 5);
INSERT INTO KEYMAP VALUES('construct', 5);
INSERT INTO KEYMAP VALUES('form', 5);
INSERT INTO KEYMAP VALUES('produce', 5);
INSERT INTO KEYMAP VALUES('generate', 5);
INSERT INTO KEYMAP VALUES('establish', 5);
INSERT INTO KEYMAP VALUES('set up', 5);
INSERT INTO KEYMAP VALUES('design', 5);
INSERT INTO KEYMAP VALUES('mold', 5);
INSERT INTO KEYMAP VALUES('forge', 5);