-- INSERT
INSERT INTO KEYMAP VALUES('add', 4);
INSERT INTO KEYMAP VALUES('introduce', 4);
INSERT INTO KEYMAP VALUES('place', 4);
INSERT INTO KEYMAP VALUES('put', 4);
INSERT INTO KEYMAP VALUES('position', 4);
INSERT INTO KEYMAP VALUES('fix', 4);
INSERT INTO KEYMAP VALUES('implant', 4);
INSERT INTO KEYMAP VALUES('infix', 4);
INSERT INTO KEYMAP VALUES('embed', 4); 
INSERT INTO KEYMAP VALUES('stick in', 4); 
INSERT INTO KEYMAP VALUES('drop in', 4);
INSERT INTO KEYMAP VALUES('tuck', 4);
