-- DROP
INSERT INTO KEYMAP VALUES('lower', 7);
INSERT INTO KEYMAP VALUES('let fall', 7);
INSERT INTO KEYMAP VALUES('release', 7);
INSERT INTO KEYMAP VALUES('let go', 7);
INSERT INTO KEYMAP VALUES('decline', 7);
INSERT INTO KEYMAP VALUES('shed', 7);
INSERT INTO KEYMAP VALUES('abandon', 7);
INSERT INTO KEYMAP VALUES('dismiss', 7);
INSERT INTO KEYMAP VALUES('eliminate', 7);
INSERT INTO KEYMAP VALUES('remove', 7);
INSERT INTO KEYMAP VALUES('cancel', 7);
INSERT INTO KEYMAP VALUES('discontinue', 7);

