-- UPDATE
INSERT INTO KEYMAP VALUES('revise', 2);
INSERT INTO KEYMAP VALUES('modify', 2);
INSERT INTO KEYMAP VALUES('change', 2);
INSERT INTO KEYMAP VALUES('adjust', 2);
INSERT INTO KEYMAP VALUES('amend', 2);
INSERT INTO KEYMAP VALUES('refresh', 2);
INSERT INTO KEYMAP VALUES('renew', 2);
INSERT INTO KEYMAP VALUES('upgrade', 2);
INSERT INTO KEYMAP VALUES('improve', 2);
INSERT INTO KEYMAP VALUES('overhaul', 2);
INSERT INTO KEYMAP VALUES('bring up to date', 2);