-- SELECT
INSERT INTO KEYMAP VALUES('pick', 1);
INSERT INTO KEYMAP VALUES('choose', 1);
INSERT INTO KEYMAP VALUES('opt', 1);
INSERT INTO KEYMAP VALUES('select', 1);
INSERT INTO KEYMAP VALUES('elect', 1);
INSERT INTO KEYMAP VALUES('single out', 1);
INSERT INTO KEYMAP VALUES('flag', 1);
INSERT INTO KEYMAP VALUES('highlight', 1);
INSERT INTO KEYMAP VALUES('tag', 1);
