-- KEYWORDS
INSERT INTO KEYWORDS VALUES('SELECT', 1);
INSERT INTO KEYWORDS VALUES('UPDATE', 2);
INSERT INTO KEYWORDS VALUES('DELETE', 3);
INSERT INTO KEYWORDS VALUES('INSERT', 4);
INSERT INTO KEYWORDS VALUES('CREATE', 5);
INSERT INTO KEYWORDS VALUES('ALTER', 6);
INSERT INTO KEYWORDS VALUES('DROP', 7);

